name: image_video_picker_example
description: Ozzy Ozmen Celik

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # pick video & image
  image_picker: ^0.6.7+1

  # play video
  video_player: ^0.10.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true